#define SFX_AMBULANCE	0
#define SFX_BEEP	1
#define SFX_BOMB	2
#define SFX_BOOM	3
#define SFX_CLICK	4
#define SFX_CLOCK	5
#define SFX_CLOSEDOOR	6
#define SFX_DRAIN	7
#define SFX_FIREPLACE	8
#define SFX_FOOTSTEPS	9
#define SFX_GATE	10
#define SFX_GHOSTLY	11
#define SFX_GLASS	12
#define SFX_GUNSHOT	13
#define SFX_HOWLING	14
#define SFX_KEYDROP	15
#define SFX_MAGIC	16
#define SFX_OPENDOOR	17
#define SFX_SECRETDOOR	18
#define SFX_TIMEWARP	19
#define SFX_UNLOCK	20
#define SFX_VACUUM	21
#define SFX_WATERDRIP	22
#define MOD_DETECTIVE	0
#define MOD_WEATHER	1
#define MSL_NSONGS	2
#define MSL_NSAMPS	48
#define MSL_BANKSIZE	50
