#ifndef __CEVENT_H__
#define __CEVENT_H__

#include "TDG.h"

#define BIT64(n) (1LL << (n))

#define MAX_EVENTS			32

enum EventType
{
	EVENT_START_GAME,
	EVENT_MURDER_DINGLE,
	EVENT_MURDER_CYNTHIA,
	EVENT_MURDER_DOCTOR,
	EVENT_MURDER_GABRIEL,
	EVENT_REMOVE_BULLETS,
	EVENT_GET_SHOT
};

/* enum EventFlag : uint64
{
	EVENTFLAG_NONE = 0,
	EVENTFLAG_SNIDE_IN_ROOM = BIT(0),
	EVENTFLAG_REVEREND_IN_ROOM = BIT(1),
	EVENTFLAG_BENTLEY_IN_ROOM = BIT(2),
	EVENTFLAG_COOK_IN_ROOM = BIT(3),
	EVENTFLAG_GABRIEL_IN_ROOM = BIT(4),
	EVENTFLAG_CYNTHIA_IN_ROOM = BIT(5),
	EVENTFLAG_PROFESSOR_IN_ROOM = BIT(6),
	EVENTFLAG_DOCTOR_IN_ROOM = BIT(7),
	EVENTFLAG_MAJOR_IN_ROOM = BIT(8),
	EVENTFLAG_DINGLE_IN_ROOM = BIT(9),
	EVENTFLAG_ANGUS_IN_ROOM = BIT(10),
	EVENTFLAG_SNIDE_NOT_IN_ROOM = BIT(11),
	EVENTFLAG_REVEREND_NOT_IN_ROOM = BIT(12),
	EVENTFLAG_BENTLEY_NOT_IN_ROOM = BIT(13),
	EVENTFLAG_COOK_NOT_IN_ROOM = BIT(14),
	EVENTFLAG_GABRIEL_NOT_IN_ROOM = BIT(15),
	EVENTFLAG_CYNTHIA_NOT_IN_ROOM = BIT(16),
	EVENTFLAG_PROFESSOR_NOT_IN_ROOM = BIT(17),
	EVENTFLAG_DOCTOR_NOT_IN_ROOM = BIT(18),
	EVENTFLAG_MAJOR_NOT_IN_ROOM = BIT(19),
	EVENTFLAG_DINGLE_NOT_IN_ROOM = BIT(20),
	EVENTFLAG_ANGUS_NOT_IN_ROOM = BIT(21),
	EVENTFLAG_GAME_OVER = BIT(22),
	EVENTFLAG_HALL1 = BIT(23),
	EVENTFLAG_HALL3 = BIT(24),
	EVENTFLAG_READY_MURDER_DINGLE = BIT(25),
	EVENTFLAG_READY_MURDER_CYNTHIA = BIT(26),
	EVENTFLAG_READY_MURDER_DOCTOR = BIT(27),
	EVENTFLAG_READY_MURDER_GABRIEL = BIT(28),
	EVENTFLAG_MURDER_DINGLE = BIT(29),
	EVENTFLAG_MURDER_CYNTHIA = BIT(30),
	EVENTFLAG_MURDER_DOCTOR = BIT64(31),
	EVENTFLAG_MURDER_GABRIEL = BIT64(32),
	EVENTFLAG_WITNESS_MURDER_DINGLE = BIT64(33),
	EVENTFLAG_WITNESS_MURDER_CYNTHIA = BIT64(34),
	EVENTFLAG_WITNESS_MURDER_DOCTOR = BIT64(35),
	EVENTFLAG_WITNESS_MURDER_GABRIEL = BIT64(36),
	EVENTFLAG_PLACE_KNIFE = BIT64(37),
	EVENTFLAG_REMOVE_BULLETS = BIT64(38),
	EVENTFLAG_LOCK_DINGLES_ROOM = BIT64(39),
	EVENTFLAG_GABRIELS_DOOR_LOCKED = BIT64(40)
}; */

const static uint64 EVENTFLAG_NONE = 0LL;
const static uint64 EVENTFLAG_SNIDE_IN_ROOM = BIT64(0);
const static uint64 EVENTFLAG_REVEREND_IN_ROOM = BIT64(1);
const static uint64 EVENTFLAG_BENTLEY_IN_ROOM = BIT64(2);
const static uint64 EVENTFLAG_COOK_IN_ROOM = BIT64(3);
const static uint64 EVENTFLAG_GABRIEL_IN_ROOM = BIT64(4);
const static uint64 EVENTFLAG_CYNTHIA_IN_ROOM = BIT64(5);
const static uint64 EVENTFLAG_PROFESSOR_IN_ROOM = BIT64(6);
const static uint64 EVENTFLAG_DOCTOR_IN_ROOM = BIT64(7);
const static uint64 EVENTFLAG_MAJOR_IN_ROOM = BIT64(8);
const static uint64 EVENTFLAG_DINGLE_IN_ROOM = BIT64(9);
const static uint64 EVENTFLAG_ANGUS_IN_ROOM = BIT64(10);
const static uint64 EVENTFLAG_SNIDE_NOT_IN_ROOM = BIT64(11);
const static uint64 EVENTFLAG_REVEREND_NOT_IN_ROOM = BIT64(12);
const static uint64 EVENTFLAG_BENTLEY_NOT_IN_ROOM = BIT64(13);
const static uint64 EVENTFLAG_COOK_NOT_IN_ROOM = BIT64(14);
const static uint64 EVENTFLAG_GABRIEL_NOT_IN_ROOM = BIT64(15);
const static uint64 EVENTFLAG_CYNTHIA_NOT_IN_ROOM = BIT64(16);
const static uint64 EVENTFLAG_PROFESSOR_NOT_IN_ROOM = BIT64(17);
const static uint64 EVENTFLAG_DOCTOR_NOT_IN_ROOM = BIT64(18);
const static uint64 EVENTFLAG_MAJOR_NOT_IN_ROOM = BIT64(19);
const static uint64 EVENTFLAG_DINGLE_NOT_IN_ROOM = BIT64(20);
const static uint64 EVENTFLAG_ANGUS_NOT_IN_ROOM = BIT64(21);
const static uint64 EVENTFLAG_GAME_OVER = BIT64(22);
const static uint64 EVENTFLAG_HALL1 = BIT64(23);
const static uint64 EVENTFLAG_HALL3 = BIT64(24);
const static uint64 EVENTFLAG_READY_MURDER_DINGLE = BIT64(25);
const static uint64 EVENTFLAG_READY_MURDER_CYNTHIA = BIT64(26);
const static uint64 EVENTFLAG_READY_MURDER_DOCTOR = BIT64(27);
const static uint64 EVENTFLAG_READY_MURDER_GABRIEL = BIT64(28);
const static uint64 EVENTFLAG_MURDER_DINGLE = BIT64(29);
const static uint64 EVENTFLAG_MURDER_CYNTHIA = BIT64(30);
const static uint64 EVENTFLAG_MURDER_DOCTOR = BIT64(31);
const static uint64 EVENTFLAG_MURDER_GABRIEL = BIT64(32);
const static uint64 EVENTFLAG_WITNESS_MURDER_DINGLE = BIT64(33);
const static uint64 EVENTFLAG_WITNESS_MURDER_CYNTHIA = BIT64(34);
const static uint64 EVENTFLAG_WITNESS_MURDER_DOCTOR = BIT64(35);
const static uint64 EVENTFLAG_WITNESS_MURDER_GABRIEL = BIT64(36);
const static uint64 EVENTFLAG_PLACE_KNIFE = BIT64(37);
const static uint64 EVENTFLAG_REMOVE_BULLETS = BIT64(38);
const static uint64 EVENTFLAG_LOCK_DINGLES_ROOM = BIT64(39);
const static uint64 EVENTFLAG_GABRIELS_DOOR_LOCKED = BIT64(40);

class CEvent
{
public:
	CEvent(EventType eventType, CTime* pEventTime, uint64 condition, uint64 action);
	~CEvent();
	
	bool Update(CTime* pCurrentTime);

	bool Done() const { return m_done; }
	
	uint64 Condition() const { return m_condition; }
	uint64 Action() const { return m_action; }
	
	EventType GetEventType() const { return m_eventType; }
	
	void SetDone(bool value) { m_done = value; }

private:
	EventType m_eventType;
	CTime* m_pEventTime;
	
	uint64 m_condition;
	uint64 m_action;
	
	bool m_done;
};

#endif
