#ifndef __CITEMCACHE_H__
#define __CITEMCACHE_H__

#include "ColMap.h"

#define MAX_ITEM_CACHE		8
#define MAX_ITEM_ARRAY		5

enum ItemCache
{
	ITEMCACHE_NONE = 0,
	ITEMCACHE_FOUR_POSTER_BED = COL_FOUR_POSTER_BED,
	ITEMCACHE_CHEST_OF_DRAWERS = COL_CHEST_OF_DRAWERS,
	ITEMCACHE_FIREPLACE = COL_FIREPLACE,
	ITEMCACHE_COAL_BUCKET = COL_COAL_BUCKET,
	ITEMCACHE_PAINTING = COL_PAINTING,
	ITEMCACHE_WOODEN_BOX = COL_WOODEN_BOX,
	ITEMCACHE_MICROWAVE = COL_MICROWAVE,
	ITEMCACHE_SIDEBOARD = COL_SIDEBOARD,
	ITEMCACHE_CUPBOARD1 = COL_CUPBOARD1,
	ITEMCACHE_CUPBOARD2 = COL_CUPBOARD2,
	ITEMCACHE_CUPBOARD3 = COL_CUPBOARD3,
	ITEMCACHE_CUPBOARD4 = COL_CUPBOARD4,
	ITEMCACHE_SINK = COL_SINK,
	ITEMCACHE_BOOKCASE1 = COL_BOOKCASE1,
	ITEMCACHE_BOOKCASE2 = COL_BOOKCASE2,
	ITEMCACHE_BOXES1 = COL_BOXES1,
	ITEMCACHE_BOXES2 = COL_BOXES2,
	ITEMCACHE_BOXES3 = COL_BOXES3,
	ITEMCACHE_BED = COL_BED,
	ITEMCACHE_CLOTHES_CUPBOARD = COL_CLOTHES_CUPBOARD,
	ITEMCACHE_CLOCK = COL_CLOCK,
	ITEMCACHE_WINDOW = COL_WINDOW,
	ITEMCACHE_DESK = COL_DESK,
	ITEMCACHE_SHELVES = COL_SHELVES,
	ITEMCACHE_LOCKED_WALL_SAFE = COL_LOCKED_WALL_SAFE,
	ITEMCACHE_OPEN_WALL_SAFE = COL_OPEN_WALL_SAFE,
	ITEMCACHE_DINGLES_BODY = COL_DINGLES_BODY,
	ITEMCACHE_PIANO_AND_A_SQUASHED_CYNTHIA_SLUDGEBUCKET = COL_PIANO_AND_A_SQUASHED_CYNTHIA_SLUDGEBUCKET,
	ITEMCACHE_GABRIELS_BODY = COL_GABRIELS_BODY,
	ITEMCACHE_STABBED_DOCTOR = COL_STABBED_DOCTOR,
	ITEMCACHE_HEADSTONE1 = COL_HEADSTONE1,
	ITEMCACHE_HEADSTONE2 = COL_HEADSTONE2,
	ITEMCACHE_FOUNTAIN_WITH_RUNNING_WATER = COL_FOUNTAIN_WITH_RUNNING_WATER,
	ITEMCACHE_FOUNTAIN_DRAINED_OF_WATER = COL_FOUNTAIN_DRAINED_OF_WATER,
	ITEMCACHE_GARGOYLE1 = COL_GARGOYLE1,
	ITEMCACHE_GARGOYLE2 = COL_GARGOYLE2,
	ITEMCACHE_GARGOYLE3 = COL_GARGOYLE3,
	ITEMCACHE_GOAT_LIKE_PAINTING = COL_GOAT_LIKE_PAINTING,
	ITEMCACHE_DESK_WITH_A_STATUE = COL_DESK_WITH_A_STATUE,
	ITEMCACHE_A_TROPHY = COL_A_TROPHY,
	ITEMCACHE_ANGUS_BOOKCASE = COL_ANGUS_BOOKCASE,
	ITEMCACHE_KNIGHT = COL_KNIGHT,
	ITEMCACHE_COUCH = COL_COUCH,
	ITEMCACHE_HOURGLASS = COL_HOURGLASS,
	ITEMCACHE_GOLDEN_SKULL = COL_GOLDEN_SKULL,
	ITEMCACHE_TABLE = COL_TABLE,
	ITEMCACHE_WASHING_MACHINE = COL_WASHING_MACHINE,
	ITEMCACHE_WASHING_BASKET = COL_WASHING_BASKET,
	ITEMCACHE_CUPBOARD = COL_CUPBOARD,
	ITEMCACHE_CABINET = COL_CABINET
};

class CItem;

class CItemCache
{
public:
	CItemCache();
	CItemCache(ItemCache itemCache);
	CItemCache(CItem* itemArray[]);
	CItemCache(ItemCache itemCache, CItem* itemArray[]);
	~CItemCache();
	
	void ClearItems();
	bool AddItem(CItem* pItem);
	bool RemoveItem(CItem* pItem);
	
private:
	ItemCache m_itemCache;
	CItem* m_itemArray[MAX_ITEM_ARRAY];
};

#endif
