#include <nds.h>

enum CollisionType
{
	COL_NOTHING_HERE = 0,
	COL_DOOR1 = 1,
	COL_DOOR2 = 2,
	COL_DOOR3 = 3,
	COL_DOOR4 = 4,
	COL_DOOR5 = 5,
	COL_DOOR6 = 6,
	COL_DOOR7 = 7,
	COL_SECRET_PASSAGE1 = 8,
	COL_SECRET_PASSAGE2 = 9,
	COL_BOOKCASE = 10,
	COL_PAINTING = 11,
	COL_SAFE = 12,
	COL_COAL_BUCKET = 13,
	COL_FIREPLACE = 14,
	COL_CLOCK = 15,
	COL_CUPBOARD = 16,
	COL_MICROWAVE = 17,
	COL_WOODEN_BOX = 18,
	COL_SINK = 19,
	COL_BOXES = 20,
	COL_CLOTHES_CUPBOARD = 21,
	COL_BED = 22,
	COL_CHEST_OF_DRAWERS = 23,
	COL_FOUR_POSTER_BED = 24,
	COL_WINDOW = 25
};

extern const u8 col_hall1[];
extern const u8 col_room1[];
