enum CollisionType
{
	COL_NOTHING_HERE = 0,
	COL_DOOR1 = 1,
	COL_DOOR2 = 2,
	COL_DOOR3 = 3,
	COL_DOOR4 = 4,
	COL_DOOR5 = 5,
	COL_DOOR6 = 6,
	COL_DOOR7 = 7,
	COL_SECRET_PASSAGE = 8,
	COL_BOOKCASE = 9,
	COL_PAINTING = 10,
	COL_SAFE = 11,
	COL_COAL_BUCKET = 12,
	COL_FIREPLACE = 13,
	COL_CLOCK = 14,
	COL_CUPBOARD = 15,
	COL_MICROWAVE = 16,
	COL_WOODEN_BOX = 17,
	COL_SINK = 18,
	COL_BOXES = 19,
	COL_CLOTHES_CUPBOARD = 20,
	COL_BED = 21,
	COL_CHEST_OF_DRAWERS = 22,
	COL_FOUR_POSTER_BED = 23,
	COL_WINDOW = 24
};

extern const char col_hall1[][];
